AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - '!**/Gemfile'
    - '!**/Rakefile'